ref_sequences:
    Evol09:  "FJ708820:FJ709040"
    Mycol13: "KJ145910:KJ145926"
    Bryol17: "MF067362:MF067375"
    Lichenol16: "KC139749:KC139751,KC139753:KC139761,KJ413197,KJ413220:KJ413226,KJ413238:KJ413244,KJ413246:KJ413250,KJ616384:KJ616388,KT861422:KT861425,KT948755:KT948756,KU954062:KU954063"
    Mycologia03: "AY257896,AY257952,AY257953,AY257900,AY257950,AY257951,AY257911,AY257912,AY257914,AY257948,AY257949,AY257943:AY257945,AY257897:AY257899,AY257913,AY257954,AY257955,AY257872:AY257875,AY257877,AY257879,AY257881,AY257883:AY257886"
    Taxon18: "MH758276:MH758314,MH758379,MH758384:MH758387,MH758389,MH758390:MH758394,MH758397,MH758398,MH758467,MH758469:MH758475,MH758478,MH758479,MH758491:MH758494,MH758500,MH758502,MH758503,MH758505:MH758509,MH758510,MH758513:MH758516,MH758518:MH758524"
    JEcol19: "MK517826:MK517838"
    SystBiol16: "KX897177:KX897401"
    FungalEcol17: "LT852805:LT853056"
    AmJBot14: "KM005774:KM005789"
    OpPhil11: "JF837354:JF837374"
    FrontMicro18: "MH734627:MH734726"
    NewPhytol13: "KC437590:KC437650"
references:
    Evol09: "O'Brien 2009 Evolution https://doi.org/10.1111/j.1558-5646.2009.00685.x"
    Mycol13: "Anstett 2013 Mycology https://doi.org/10.1080/21501203.2013.875955"
    Bryol17: "Joneson 2017 Bryologist https://doi.org/10.1639/0007-2745-120.4.371"
    Lichenol16: "MANOHARAN-BASIL 2016 Lichenologist https://doi.org/10.1017/S0024282916000414"
    Mycologia03: "Miadlikowska 2003 Mycologia https://doi.org/10.1080/15572536.2004.11833027"
    Taxon18: "Magain 2018 Taxon https://doi.org/10.12705/675.3"
    JEcol19: "Chagnon 2019 J. Ecol. https://doi.org/10.1111/1365-2745.13207"
    SystBiol16: "Magain 2016 Syst. Biol. https://doi.org/10.1093/sysbio/syw065"
    FungalEcol17: "Juriado 2017 Fungal Ecol. https://doi.org/10.1016/j.funeco.2017.08.004"
    AmJBot14: "Miadlikowska 2014 Am. J. Bot. https://doi.org/10.3732/ajb.1400267"
    OpPhil11: "Lendemer 2011 Opuscula Philolichenum http://sweetgum.nybg.org/science/op/biblio_list.php?BucVolume_tab=9"
    FrontMicro18: "Pardo-De la Hoz 2018 Frontiers in Microbiology https://doi.org/10.3389/fmicb.2018.02770"
    NewPhytol13: "O'Brien 2013 New Phytologist https://doi.org/10.1111/nph.12165"
complexes:
    #section Hydrothyriae
    Phydro:
        - P. hydrothyria
        - P. gowardii
        - P. aquatica
    # section Peltidea
    Paphth:
        - P. aphthosa
        - P. britannica
        - P. malacea
        - P. chionophila
        - P. frippii
    # section Chloropeltigera
    Pleu:
        - P. leucophlebia
        - P. latiloba
        - P. nigripunctata
    # section Phlebia
    Pven: 
        - P. venosa
    # section Polydactylon
    Ppoly:
        - P. polydactylon
        - P. nana
    #Pdol:
        - P. dolichorrhiza
        - P. pulverulenta
        - P. hymenina
        - P. pacifica
        - P. truculenta
        - P. hawaiensis
        - P. occidentalis
    #Pscab:
        - P. scabrosa
        - P. melanorrhiza
        - P. neopolydactyla
    # section Horizontales
    Phor:
        - P. horizontalis
        - P. elisabethae
        - P. andensis
    #Pcol:
        - P. collina
        - P. neckeri
        - P. polydactyloides
        - P. phyllidiosa
    # section Retifoveatae
    #Pret:
    #    - P. retifoveata
    # section Peltigera
    Pdid: # clade 4
        - P. didactyla
        - P. extenuata
        - P. vainioi
        - P. castanea
        - P. sorediifera
    Ppono: # clade 5
        - P. ponojensis
        - P. monticola
        - P. antarctica
        - P. scotteri
    Pruf: # clade 6
        - P. rufescens
        - P. neorufescens
        - P. lepidophora
        - P. laciniata
        - P. soredians
        - P. papuana
        - P. granulosa
        - P. friesiorum
        - P. wulingensis
        - P. rufescentiformis
        - P. fuscoponojensis
    Pcin: # clade 7
        - P. cinnamomea
        - P. neocanina
        - P. erioderma
        - P. montis-wilhelmii
    Pmemb: # clade 8
        - P. degenii
        - P. membranacea
        - P. tereziana
    Pcan: # clade 9
        - P. canina 
        - P. koponenii
        - P. praetextata
        - P. islandica
        - P. evansiana
        - P. fuscopraetextata
        - P. pallidorufescens
        - P. austroamericana
    Pkris:
        - P. kristinssonii      
manual_refs:
    AY257896: Pcan
    AY257897: Pcin
    AY257913: Pcin
    AY257914: Pcan
    AY257886: Ppono
    FJ708907: Pcan
    FJ708908: Pcan
    FJ708909: Pcan
    FJ708910: Pcan
    KC139757: Pcan
    KC139759: Pcan
    KC139760: Pcan
    KC139761: Pcan
    KJ413238: Pcan
    KJ413239: Pcan
    KJ413240: Pcan
    KJ413241: Pcan
    KJ413242: Pcan
    KJ413243: Pcan
    KJ413244: Pcan
excluded_query:
    - SLJ4375_Peltigera_ponojensis_ITS4_RevComp
    - SLJ4360_Peltigera_islandica_ITS4_RevComp
excluded_ref:
    - LT852921.1
